# Generated by Django 5.0.2 on 2024-02-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=10)),
                ('long_url', models.URLField()),
                ('response_json', models.JSONField()),
                ('response_code', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('url_key', models.CharField(max_length=20)),
            ],
        ),
    ]
