# Generated by Django 5.0.2 on 2024-02-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlaction',
            name='long_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='urlaction',
            name='response_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='urlaction',
            name='response_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='urlaction',
            name='url_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
