# Generated by Django 5.0.2 on 2024-02-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0002_alter_urlaction_long_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlaction',
            name='action_type',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=10),
        ),
    ]
