# Generated by Django 5.0.2 on 2024-02-21 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0004_alter_urlaction_url_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlaction',
            name='long_url',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
    ]
